[package]
name = "trunk-template"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[build-dependencies]
wasm-bindgen-cli = "0.2.78"
